/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.glacier.app;

import org.apache.commons.text.WordUtils;

/**
 * @author glacier
 */
public class App {
    public static void main(String[] args) {
        System.out.println(WordUtils.capitalize("hello world"));
    }
}
